version: "3.8"
services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: api_c
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - /app/node_modules
  myblog:
    build: 
      context: ./myblog
      dockerfile: Dockerfile
    container_name: myblog_c
    ports:
      - '3000:3000'
    stdin_open: true